name: docify-certbot

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./deployment/certbot/www:/var/www/certbot
      - ./deployment/certbot/conf:/etc/letsencrypt
    # command: certonly --webroot --webroot-path=/var/www/certbot --email ksss90411@gmail.com --agree-tos --no-eff-email -d docify.cc -d www.docify.cc -d status.docify.cc
