worker_processes auto;

events {
  worker_connections 1024;
}

http {
    include mime.types;

    upstream docify {
        server web:3001;
    }

    upstream docify-excel-service {
        server excel-service:3002;
    }

    server {
        listen 80;
        server_name docify.cc www.docify.cc;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name docify.cc www.docify.cc status.docify.cc;

        ssl_certificate     /etc/letsencrypt/live/docify.cc/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/docify.cc/privkey.pem;

        location /.well-known/acme-challenge/ {
          root /var/www/certbot;
        }

        location / {
           proxy_pass http://docify;
           proxy_set_header Host $http_host;
           proxy_set_header X-Forwarded-Host $http_host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_set_header X-Forwarded-Port $server_port;

           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
        }

        location /excel-service/ {
          proxy_pass http://docify-excel-service/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Port $server_port;
        }
    }

    upstream uptime-kuma {
      server uptime-kuma:3003;
    }

    server {
        listen 443 ssl;
        server_name status.docify.cc;

        ssl_certificate     /etc/letsencrypt/live/docify.cc/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/docify.cc/privkey.pem;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://uptime-kuma;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
  }
}
