name: Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: cypress-io/github-action@v7.4.3
        with:
          build: bun run build
          start: bun run dev
        env:
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

  lint:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run lint:github

  migrate:
    runs-on: ubuntu-latest
    environment: production
    needs: cypress
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - name: Run migrations
        working-directory: packages/db
        run: bun run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - migrate

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/adil/Docify
            git pull origin main
            docker compose up -d --build web excel-service nginx
            docker compose up -d --force-recreate nginx

            docker exec docify-nginx-1 nginx -t
            docker image prune -f
            docker builder prune -f
